version: '3.5'

services:
  app:
    build: .
    container_name: app
    image: app
    environment:
      PG_URL: 'postgres://postgres:root@postgres:5432/postgres?sslmode=disable'
      RATE_LIMITER: 'ENABLE'
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg-data: 
    name: order_delivery_service-pg-data