version: '3.5'

services:
  test:
    build: .
    container_name: test
    image: test
    environment:
      PG_URL: 'postgres://postgres:root@postgres:5432/postgres?sslmode=disable'
      RATE_LIMITER: 'DISABLE'
    ports:
      - 8081:8080
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: test_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    image: postgres:15-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  integration:
    build:
      context: .
      dockerfile: integration_tests/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - test

volumes:
  pg-data: 
    name: test_order_delivery_service-pg-data
