app:
  name: 'yandex_lavka'
  version: '0.1.0'

http:
  port: '8080'

postgres:
  dialect: 'postgres'
  # pg_url: 'postgres://admin:root@postgres:5432/postgres'
  pool_max: 2

logger:
  log_level: 'debug'
